swagger: '2.0'
info:
  title: DeepFake Detector API
  description: REST API for media detection
  version: 1.0.0

host: YOUR_GATEWAY_HOST

x-google-backend:
  address: https://YOUR_CLOUD_RUN_URL # or Cloud Function URL

paths:
  /detect:
    post:
      summary: Run deepfake detection
      operationId: detectDeepfake
      responses:
        '200':
          description: OK
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: 'apiKey'
    name: 'Authorization'
    in: 'header'
