# Model Configuration
model:
  name: "efficientnet_b4"
  num_classes: 2
  pretrained: true
  dropout: 0.3

# Training Configuration (Optimized for 5.4GB memory)
training:
  batch_size: 8          # Reduced from 32 to fit memory
  epochs: 30             # Reduced from 50 for faster completion
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 8            # Reduced patience

# Data Configuration
data:
  input_size: 224
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  augmentation: true

# Paths
paths:
  data_dir: "data/"
  models_dir: "checkpoints/"
  logs_dir: "logs/"
  results_dir: "results/"
