
# Lightweight configurations for CPU training
mobilenet_v2:
  frame_encoder: "mobilenet_v2"
  temporal_model: "lstm"
  hidden_size: 256
  num_layers: 2
  bidirectional: false

resnet18:
  frame_encoder: "resnet18"
  temporal_model: "gru"
  hidden_size: 256
  num_layers: 2
  bidirectional: false

# Memory-efficient configuration
minimal:
  frame_encoder: "mobilenet_v2"
  temporal_model: null  
  max_frames: 8         
  frame_size: [112, 112]  

# Balanced configuration (recommended)
balanced:
  frame_encoder: "mobilenet_v2"
  temporal_model: "lstm"
  max_frames: 16
  frame_size: [224, 224]
  hidden_size: 256