displayName: "video-deepfake-detector-training"
jobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
    replicaCount: 1
    containerSpec:
      imageUri: "gcr.io/cloud-aiplatform/training/pytorch-cpu.1-13:latest"
      command:
      - "python"
      - "scripts/vertex_ai_training_cpu_optimized.py"
      args:
      - "--bucket-name=second-bucket-video-deepfake"
      - "--epochs=20"
      - "--batch-size=4"
      - "--max-frames=16"
      - "--frame-encoder=mobilenet_v2"
      - "--temporal-model=lstm"
      env:
      - name: "GOOGLE_CLOUD_PROJECT"
        value: "video-deep-fake-detector"
  serviceAccount: "vertex-ai-key@video-deep-fake-detector.iam.gserviceaccount.com"