

displayName: "video-deepfake-detector-training"
jobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"  # 4 vCPUs, 15GB RAM (cost-effective)
      # For GPU training, use: "n1-standard-4"  
      # acceleratorType: "NVIDIA_TESLA_T4"
      # acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: "gcr.io/cloud-aiplatform/training/pytorch-cpu.1-13:latest"
      # For GPU: "gcr.io/cloud-aiplatform/training/pytorch-gpu.1-13:latest"
      command:
      - "python"
      - "scripts/vertex_ai_training_cpu_optimized.py"
      args:
      - "--bucket-name=second-bucket-video-deepfake"
      - "--epochs=20"
      - "--batch-size=4"
      - "--max-frames=16"
      - "--frame-encoder=mobilenet_v2"
      - "--temporal-model=lstm"
      env:
      - name: "GOOGLE_CLOUD_PROJECT"
        value: "YOUR_PROJECT_ID"  # Replace with your project ID
      - name: "GOOGLE_APPLICATION_CREDENTIALS"
        value: "/gcs/service-account-key.json"
  serviceAccount: "video-deepfake-trainer@YOUR_PROJECT_ID.iam.gserviceaccount.com"