name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: deepfake-detector-455108
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/deepfake-detector-455108/deepfake-detector .
          docker push gcr.io/deepfake-detector-455108/deepfake-detector

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deepfake-detector \
            --image gcr.io/deepfake-detector-455108/deepfake-detector \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
